# mysql-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local # Etiqueta opcional para identificarlo
spec:
  capacity:
    storage: 5Gi # Debe coincidir o ser mayor que la solicitud del PVC
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql" # Ruta donde se guardarán los datos de MySQL en el nodo
